# Generated by Django 5.1.7 on 2026-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEIKI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='record_type',
            field=models.CharField(choices=[('in', 'Time In'), ('out', 'Time Out')], default='in', max_length=3),
        ),
    ]
