# Generated by Django 5.1.7 on 2026-04-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEIKI', '0002_timerecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
