# Generated by Django 5.1.7 on 2026-04-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEIKI', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='required_hours',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Total hours needed to render', max_digits=5),
        ),
    ]
