# Generated by Django 5.1.7 on 2026-04-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEIKI', '0005_alter_userprofile_required_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
