services:
  - type: web
    name: seiki
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn SEIKI.wsgi:application
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        fromService:
          name: seiki
          property: host
